# Generated by Django 3.1.2 on 2021-05-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('book_author', models.CharField(max_length=50, verbose_name='著者')),
                ('date', models.DateField(verbose_name='読んだ日付')),
                ('text', models.TextField(verbose_name='感想')),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
